modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/DavidQF555/EntityEnchantment/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/DavidQF555/EntityEnchantment"
updateJSONURL = "https://raw.githubusercontent.com/DavidQF555/EntityEnchantment/update/update.json"
logoFile = "logo.png"
authors = "${mod_authors}"
description = 'This mod adds enchantments to entities.'
[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
