modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/DavidQF555/EntityEnchantment/issues"
[[mods]]
modId = "entity_enchantment"
version = "${file.jarVersion}"
displayName = "Entity Enchantment"
displayURL = "https://github.com/DavidQF555/EntityEnchantment"
updateJSONURL = "https://raw.githubusercontent.com/DavidQF555/EntityEnchantment/update/update.json"
logoFile = "logo.png"
authors = "DavidQF555"
description = 'This mod adds enchantments to entities.'
[[dependencies.entity_enchantment]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.entity_enchantment]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
